FROM anapsix/alpine-java
#Configure the production environment
RUN apk update
RUN apk add mongodb

WORKDIR /CPD
COPY --from=gdimodica/beng-repo:cpd-develop /app/target/deploy-bundle .
RUN chmod 754 *.sh


