Collaborative Procedure Designer
================================

The Collaborative Procedure Designer (CPD) is a web server&application that provides services to draw administrative
procedures in a collaborative way.

= Getting started
These instructions will get you a copy of the project up and running on your machine for testing or development
purposes.

* The “<<build,Building the application>>” section describes how to produce an executable copy of the application.
* The “<<run,Running the application>>” section describes how to set up the runtime environment and execute the
  application.

= [[build]]Building the application

This is a Java Maven project.

== [[pom]]pom.xml

A Project Object Model (POM) is the fundamental unit of work in Maven. There are two *build profiles* of the POM that
deserve attention: *production* and *develop*, depending on whether the project is going to be built for production or
for development purposes. Each profile uses one of the two Java properties files created following the configuration
instructions in the “<<properties,example.properties>>” section:

* `production.properties`: represents the end configuration file to use for building the test server and will usually
  only be configured once, based on your target server deploy configuration;
* `develop.properties`: this (optional) file has to be used when you want to try the application locally in your
  development environment (e.g. eclipse) and try some different config parameters without touching the
  `production.properties`.

== [[build-pre]]Build prerequisites

In order to produce an executable copy of the application you'll need the following:

* Java Development Kit 8.x
* Maven 3

== Configuration

The CPD's root folder contains *four* files to support the configuration, build and deploy of the server:

  1. `example.properties`
  2. `self-signed-keystore.sh`
  3. `prepare-bundle.sh`
  4. `deploy.sh`

Of these, just the *first* one needs to be used for the actual configurations. The last three are helper scripts that
can be used in order to simplify the build and deployment phases.

=== [[properties]]example.properties

This is an example Java properties file that contains all the configuration parameters for the application.

The POM handles two Java properties files called `production.properties` and `develop.properties`. Create the
`production.properties` by *making a copy of this file* and replacing the property values accordingly. If you're going
to test different configurations in your IDE, create the `develop.properties` in the same way and refer to the “<<ide,
Running from your favourite development environment>>” section for further configurations.

.*Please make sure to review at least the values for this main properties*:

* `cpd.ssl.enabled`: `true` or `false` depending on whether you want to use https or http (this can impact on
  `cpd.server.scheme` and `cpd.server.allowedOriginPattern` properties, check and revise them accordingly);
* `cpd.ssl.keystore.filename` (only if `cpd.ssl.enabled=true`): the path to the jks keystore file. Can be absolute or
  relative to the CPD home (e.g. `/home/citizenpedia/cpd-server/keystore.jks` or just `keystore.jks`);

IMPORTANT: If you plan to use your own signed certificate, make sure it is given to the application in jsk format. If
           you don't own a signed certificate, you can create a jks self signed one by using the <<self-signed,
           `self-signed-keystore.sh`>> script.

* `cpd.ssl.keystore.password` (only if `cpd.ssl.enabled=true`): the password of the keystore;
* `cpd.server.scheme`: `https` or `http` depending on whether you want to use ssl on unencrypted connections (see
  `cpd.ssl.enabled`);
* `cpd.server.hostname`: the hostname or the ip address of the machine executing the application (this can be
  `localhost` if you're planning to access the application locally);
* `cpd.server.port`: the port to use;
* `cpd.server.baseHref`: the *base href* of the server, must start and end with a `/` character (e.g. `/` or `/cpd/`);
* `cpd.server.allowedOriginPattern`: this is a *regex pattern* for link:http://www.w3.org/TR/cors[CORS] allowed origin
  calls (use `*` to allow calls from the entire planet, but for security reasons it is always best to put in only the
  origins that will *actually* use the API, e.g. `http:\\\\/\\\\/localhost:(8080|8901)`;

WARNING: Remember that in Java properties files the double backslash `\\` must be escaped two times: `\\\\`).

* `cpd.mongodb.host`: the mongodb hostname;
* `cpd.mongodb.port`: the mongodb port;
* `cpd.mongodb.username`: the mongodb username (if no user it must be left blank);
* `cpd.mongodb.password`: the mongodb password for user (leave blank in case of none);
* `cpd.oauth2.host`: the oauth2 hostname to send to the authority (e.g. `http://localhost:8901`);

NOTE: `cpd.oauth2.host` can differ from `cpd.server.hostname` since the server instance can be running behind a proxy
      server. In this case it is normal to have `cpd.server.hostname=localhost` and
      `cpd.oauth2.host=<my public domain name>`.

* `cpd.oauth2.client.id`: the oauth2 client id to use;
* `cpd.oauth2.client.secret`: the oauth2 client secret to use.

.google OAuth2 configuration
====

In case you want to test google OAuth2 but don't have an API account, create a project in your
link:https://console.developers.google.com/apis/credentials[Google API Mangement Console]
and then create the OAuth client ID for the web application.

In order to use google OAuth2 service, you have to add a redirect callback URI for every different `cpd.oauth2.host`
and/or `cpd.server.baseHref` the user can utilize to access the application in the _authorized redirect URI list_.

The URI to put in your  console must be written in the following form:

  http[s]://<cpd.oauth2.host><cpd.server.baseHref>auth/callback?redirect_uri=<cpd.server.baseHref>auth/google/login/handler

e.g. using `cpd.oauth2.host=localhost:8901` and `cpd.server.baseHref=/cpd/`:

  http://localhost:8901/cpd/auth/callback?redirect_uri=/cpd/auth/google/login/handler

====

=== [[self-signed]]self-signed-keystore.sh

If you need to test the server in ssl (https) mode but don't own a signed certificate, this utility script will generate
a new Java keystore storing a self-signed certificate by using the JRE keytool utility. It has pre-set values to produce
a keystore named `keystore.jks` with alias `simpatico` and password `simpatico`. `<filename>`, `<alias>` and
`<password>` can be passed as input arguments. Type `./self-signed-keystore.sh --help` for details.

After the script is launched, the Java keytool will ask you to fill in the prompts for your organization information.
*When it asks for your first and last name, enter the domain name of the server that users will be entering to connect
to the CPD application* (e.g. `www.my-beautiful-site.com`).

=== [[bundle]]prepare-bundle.sh

This script creates a bundle ready for deployment. It expects an input parameter between one of these two possible
values: `production` or `develop`. In the case no parameter is given, it will be assumed `production` by default.
You can inspect the file to understand how the `deploy-bundle` is set up.

The final bundle will be found under the `target/deploy-bundle` directory. That directory can be copied to the target
machine and renamed to your liking. The application can then be started and stopped with the provided `start.sh` and
`stop.sh` scripts respectively.

IMPORTANT: Before manually launching the deployed <<bundle,bundle>> with `start.sh`, make sure the machine you're going
           to run the server satisfies the <<run-pre,Runtime prerequisites>>.

CAUTION: If the application is configured for ssl and you used a relative path in the `cpd.keystore.filename`, make sure
         the path is relative to the files immediately under the deployed bundle.

=== [[deploy]]deploy.sh

This script has been added to simplify the deployment of the production bundle by

1. invoking the <<bundle,`prepare-bundle.sh production`>> command;
2. copying via ssh the produced `deploy-bundle` as `cpd-server` under the home of the given user (i.e.
   `/home/<user>/cpd-server`).

The script will eventually stop the running instance of the application before the ssh copy and always start the newly
deployed application after the ssh copy.

IMPORTANT: Before launching the `deploy.sh` script, make sure the ssh target machine you're deploying the application
           satisfies the <<run-pre,Runtime prerequisites>>.

The `deploy.sh` script requires *two* mandatory input parameters:

* the `USERNAME` of the user account to be used on the remote machine. The application will run with that user's
  privileges;

WARNING: Never launch the application as `root` user!

* the `SERVER` hostname or ip address of the remote machine where the application will be deployed (this should be equal
  to the `cpd.server.hostname` property value of the `production.properties` file).

= [[run]]Running the application

== [[run-pre]]Runtime prerequisites

The CPD runs on *nix equipped machines. Before trying to launch the server, make sure the following
softwares/runtimes/libraries are available at the target machine:

* Java Runtime Environment 8.x
* MongoDB 3.4

== Running from the produced deploy bundle

If built with <<bundle,`prepare-bundle.sh`>>, the application can be started with the `start.sh` script that can be
found inside the bundled package.

If built and deployed with <<deploy,`deploy.sh`>>, the application should have been started automatically.

In both cases, the application can be stopped using the `stop.sh` script.

== [[ide]]Running from your favourite development environment

Make sure your development environment satisfies both the “<<build-pre,Build prerequisites>>” and the “<<run-pre,
Running prerequisites>>”.

=== IDE configuration

There are extra configuration steps that must be taken for development purpose. The application expects the following
two directories:

  1. `./conf/`: directory containing the generated `config.json` configuration file;
  2. `./web/`: directory containing the static resources to be served.

So, create them as symbolic links in the directory you will launch the application.

*Assuming you'll run the launch command from the project root*:

  1. `ln -s target/deploy-bundle/conf conf`;
  2. `ln -s target/deploy-bundle/web web`.

IMPORTANT: Make sure the active POM profile is `develop`.

The configuration parameters can be changed in the `develop.properties` file (see the “<<properties,
example.properties>>” section).

=== Compilation

`mvn clean package [-P develop]`

will generate a `cpd-server-[version]-fat.jar` Java *fat jar*, which is a standalone _all-in-one_ executable jar. +
Maven will automatically filter the `config.json` file based on the `develop` profile and put it in the
`target/deploy-bundle/conf` directory for you.

NOTE: If no profile is passed to the `mvn` command, maven will default to `develop`.

=== Execution

`java -jar target/cpd-server-[version]-fat.jar`

Alternatively, you can configure you development environment to launch the application by setting these launcher
configuration:

* main class: `it.beng.microservice.common.Launcher`
* arguments: `run it.beng.modeler.microservice.ModelerConfigVerticle`


