Collaborative Procedure Designer
================================

The Collaborative Procedure Designer (CPD) is a web application that provides services to draw administrative procedures
in a collaborative way.

= Getting started
This is a Java maven project. These instructions will get you a copy of the project up and running on your local machine
for testing and development purposes. Basically, you can play with the software either for testing (see <<production,
Production>> section) or for development (see <<development, Development>> section) purpose.

= Prerequisites

The CPD runs on *nix equipped machines. Before trying to install, make sure the following softwares/runtimes/libraries
are available at the target machine:

* Java Runtime Environment 8.x
* MongoDB 3.4

= Configuration

The CPD's root folder contains *four* files to support the configuration:

  1. `example.properties`
  2. `pom.xml`
  3. `self-signed-keystore.sh`
  4. `deploy.sh`

Of these, just the *first* one needs to be used for the actual configuration.

In the following, a description of each file is outlined.

== [[properties]]example.properties

This is an example Java properties file that contains all the configuration parameters for the application.

The maven <<pom,pom.xml>> handles two properties file called `develop.properties` and `production.properties`. Create
both of them by *making a copy of this file* and replacing the property values accordingly.

Please make sure to overwrite at least the values for this particular properties:

* `cpd.keystore.filename`: the path to the jks keystore file. Can be absolute or relative to the CPD home
   (e.g. `/home/citizenpedia/cpd-server/keystore.jks` or just `keystore.jks`);
* `cpd.keystore.password`: the password of the keystore;
* `cpd.server.hostname`: the hostname or the ip address of the machine executing the application (probably you will
  leave `localhost` in the `develop.properties` file);
* `cpd.server.port`: the port to use;
* `cpd.server.allowedOriginPattern`: this is a *regex pattern* for allowed cross origins calls (remember that in Java
  properties files the double backslash `\\` must be escaped two times: `\\\\`);
* `cpd.mongodb.host`, `cpd.mongodb.port`, `cpd.mongodb.username`, `cpd.mongodb.password`: the mongodb properties;
* `cpd.oauth2.client.id`: the oauth2 client id to use;
* `cpd.oauth2.client.secret`: the oauth2 client secret to use.

== [[pom]]pom.xml

There are two profile sections of the `pom.xml` file that deserve attention: *production* and *develop*, depending on
whether the software is going to be built for production or for development purposes. Each profile uses one of the two
properties files created in the <<properties,previous>> section: `develop.properties` and `production.properties`.

== self-signed-keystore.sh

This is an utility script to generate a Java keystore storing a self-signed certificate. It has pre-set values to
produce a keystore named +keystore.jks+ with alias `simpatico` and password `simpatico`. You may run this script to
generate a server certificate in the case that you do not already own one. Either the case, make sure to have your
server's certificate in the _Java keystore format_ (`.jks`).

The script accepts <alias>, <password> and <filename> as arguments. Type `./self-signed-keystore.sh --help` for details.

After the script is launched, the Java keytool will ask you to fill in the prompts for your organization information.
When it asks for your first and last name, enter the domain name of the server that users will be entering to connect
to the CPD server (e.g. www.citizenpedia.com).

== deploy.sh

This script has been added to simplify the deployment of the production CPD version on the remote production server via
ssh. You can inspect it to understand how the `deploy-bundle` is set up. The script is in charge of compiling the
production version of the project and copy the produced bundle on the production server (a remote machine).

Please refer to the <<production,next>> section for the prerequisites.

= [[production]]Production

Before launching the `deploy.sh` script, make sure the machine you're running the script is equipped with:

* Java Development Kit 8.x
* Maven 3

The `deploy.sh` script requires *two* mandatory input parameters:

* the `USERNAME` of the user account to be used on the remote machine. The application will run with that user's
  privileges;
* the `SERVER` hostname or ip address of the remote machine where the application will be deployed (this should be equal
  to the `cpd.server.hostname` property value of the `production.properties` file).

= [[development]]Development

Make sure your development environment is using:

* Java Development Kit 8.x
* Maven 3

== Configuration

There are extra configuration steps that must be taken for development purpose. The application expects the following
two directories:

  1. `./conf/`: directory containing the generated `config.json` configuration file; +
  2. `./web/`: directory containing the static resources to be served.

So, create them as symbolic links on the folder you will launch the application.

*Assuming you'll run the launch command from the project root*:

  1. `ln -s target/deploy-bundle/conf conf`; +
  2. `ln -s target/deploy-bundle/web web`.

The configuration parameters can be changed in the `develop.properties` file (see the <<properties,properties>>
section).

== Compilation

`mvn clean (package|install) [-P (develop|production)]`

will generate a `cpd-server-[version]-fat.jar` Java *fat jar*, which is a standalone _all-in-one_ executable jar. +
Maven will take care of the `config.json` file filtering based on the selected profile (‘develop’ or ‘production’) and
put it in the `target/deploy-bundle/conf` directory for you.

If no profile is passed to the `mvn` command, maven will default to `develop`.

== Execution

`java -jar target/cpd-server-[version]-fat.jar`

Alternatively, you can configure you development environment to launch the application by setting these launcher
configuration:

* main class: `it.beng.microservice.common.Launcher`
* arguments: `run it.beng.modeler.microservice.ModelerConfigVerticle`


