Collaborative Procedure Designer
================================

The Collaborative Procedure Designer (CPD) is a web application that provides services to draw administrative procedures
in a collaborative way.

= Getting started
This is a Java maven project. These instructions will get you a copy of the project up and running on your local machine
for testing and development purposes. Basically, you can play with the software either for testing (see <<production,
Production>> section) or for development (see <<develop, Development>> section) purpose.

== [[pom]]pom.xml

There are two profile sections of the `pom.xml` file that deserve attention: *production* and *develop*, depending on
whether the software is going to be built for production or for development purposes. Each profile uses one of the two
Java properties files created following the instructions in the <<properties,example.properties>> section:
`develop.properties` and `production.properties`.

= [[runtime]]Runtime prerequisites

The CPD runs on *nix equipped machines. Before trying to launch the server, make sure the following
softwares/runtimes/libraries are available at the target machine:

* Java Runtime Environment 8.x
* MongoDB 3.4

= [[development]]Development prerequisites

To build the project you will need:

* Java Development Kit 8.x
* Maven 3

= Configuration

The CPD's root folder contains *four* files to support the configuration, build and deploy of the server:

  1. `example.properties`
  2. `self-signed-keystore.sh`
  3. `prepare-bundle.sh`
  4. `deploy.sh`

Of these, just the *first* one needs to be used for the actual configurations. The last three are helper scripts that
can be used in order to simplify the build and deployment phases.

== [[properties]]example.properties

This is an example Java properties file that contains all the configuration parameters for the application.

The maven <<pom,pom.xml>> handles two Java properties file called `develop.properties` and `production.properties`.
Create both of them by *making a copy of this file* and replacing the property values accordingly.

.*Please make sure to review at least the values for this main properties*:

* `cpd.ssl.enabled`: `true` or `false` depending on whether you want to use https or http (this can impact on
  `cpd.server.scheme` and `cpd.server.allowedOriginPattern` properties, check and revise them accordingly)
* `cpd.ssl.keystore.filename` (only if `cpd.ssl.enabled=true`): the path to the jks keystore file. Can be absolute or relative to the CPD home
   (e.g. `/home/citizenpedia/cpd-server/keystore.jks` or just `keystore.jks`);
* `cpd.ssl.keystore.password` (only if `cpd.ssl.enabled=true`): the password of the keystore;
* `cpd.server.scheme`: `https` or `http` depending on whether you want to use ssl on unencrypted connections (see
  `cpd.ssl.enabled`).
* `cpd.server.hostname`: the hostname or the ip address of the machine executing the application (probably you will
  leave `localhost` in the `develop.properties` file and change it only in the `production.properties`);
* `cpd.server.port`: the port to use;
* `cpd.server.allowedOriginPattern`: this is a *regex pattern* for allowed cross origins calls (remember that in Java
  properties files the double backslash `\\` must be escaped two times: `\\\\`);
* `cpd.mongodb.host`: the mongodb hostname;
* `cpd.mongodb.port`: the mongodb port;
* `cpd.mongodb.username`: the mongodb username (if no user it must be left blank);
* `cpd.mongodb.password`: the mongodb password for user (leave blank in case of none);
* `cpd.oauth2.client.id`: the oauth2 client id to use;
* `cpd.oauth2.client.secret`: the oauth2 client secret to use.

== self-signed-keystore.sh

This script uses the JRE keytool utility.

This is an utility script to generate a Java keystore storing a self-signed certificate. It has pre-set values to
produce a keystore named +keystore.jks+ with alias `simpatico` and password `simpatico`. You may run this script to
generate a server certificate in the case that you do not already own one. Either the case, make sure to have your
server's certificate in the _Java keystore format_ (`.jks`).

The script accepts <alias>, <password> and <filename> as arguments. Type `./self-signed-keystore.sh --help` for details.

After the script is launched, the Java keytool will ask you to fill in the prompts for your organization information. +
*When it asks for your first and last name, enter the domain name of the server that users will be entering to connect
to the CPD server* (e.g. “www.citizenpedia.com”).

== prepare-bundle.sh

Before running this script make sure the machine satisfies the <<development,Development prerequisites>>.

This script creates the bundle ready for deployment. It expects an input parameter between one of these two possible
values: `develop` or `production`. In the case no parameter is given, it will assume `production` by default. You can
inspect the file to understand how the `deploy-bundle` is set up.

The final bundle will be placed un the `target/deploy-bundle` directory. That directory can be copied to the target
machine and renamed to your liking. The server can then be started and stopped using the bundled `start.sh` and
`stop.sh` scripts.

If you used a relative path in the `cpd.keystore.filename`, make sure that path is relative to the position where the
`start.sh` script is.

== deploy.sh

Before running this script make sure the machine satisfies the <<development,Development prerequisites>>.

This script has been added to simplify the deployment of the production bundle on the remote production server via ssh.
The script is in charge of compiling the production version of the project and copy the produced bundle in the home of
the given user under the `cpd-server` directory (e.g. `/home/cpd/cpd-server`). The script will eventually stop any
running instance of the cpd-server before the ssh copy and always start the new cpd-server after the ssh copy.

Please refer to the <<runtime,Runtime prerequisites>> section for the target machine prerequisites.

= [[production]]Production

Before launching the `deploy.sh` script (or before manually launching the deployed bundle with `start.sh`), make sure
the machine you're going to execute the server is equipped with:

* Java Runtime Environment 8.x
* MongoDB 3.4

The `deploy.sh` script requires *two* mandatory input parameters:

* the `USERNAME` of the user account to be used on the remote machine. The application will run with that user's
  privileges;
* the `SERVER` hostname or ip address of the remote machine where the application will be deployed (this should be equal
  to the `cpd.server.hostname` property value of the `production.properties` file).

= Development environment

Make sure your development environment is using the <<development,Development prerequisites>>.

== Configuration

There are extra configuration steps that must be taken for development purpose. The application expects the following
two directories:

  1. `./conf/`: directory containing the generated `config.json` configuration file;
  2. `./web/`: directory containing the static resources to be served.

So, create them as symbolic links on the folder you will launch the application.

*Assuming you'll run the launch command from the project root*:

  1. `ln -s target/deploy-bundle/conf conf`;
  2. `ln -s target/deploy-bundle/web web`.

The configuration parameters can be changed in the `develop.properties` file (see the <<properties,properties>>
section).

== Compilation

`mvn clean (package|install) [-P (develop|production)]`

will generate a `cpd-server-[version]-fat.jar` Java *fat jar*, which is a standalone _all-in-one_ executable jar. +
Maven will take automatically filter the `config.json` file based on the selected profile (‘develop’ or ‘production’)
and put it in the `target/deploy-bundle/conf` directory for you.

If no profile is passed to the `mvn` command, maven will default to `develop`.

== Execution

For local execution the <<runtime,Runtime prerequisites>> must be satisfied in the development machine.

`java -jar target/cpd-server-[version]-fat.jar`

Alternatively, you can configure you development environment to launch the application by setting these launcher
configuration:

* main class: `it.beng.microservice.common.Launcher`
* arguments: `run it.beng.modeler.microservice.ModelerConfigVerticle`


