#!/bin/bash

#PRODUCTION DIRS AND FILES
CONFDIR=./conf
WEBASSETSCONFDIR=./web/assets/conf/
WEBSWAGGERUIDIR=./web/swagger-ui/
WEBASSETSSWAGGERDIR=./web/assets/swagger/
WEBROOTEN=./web/ROOT/en/
WEBROOTIT=./web/ROOT/it/
WEBROOTES=./web/ROOT/es/
WEBROOTGL=./web/ROOT/gl/

PRODUCTIONFILE=./.properties
DOCKERFILE=./docker.properties
JSONCONF1=$CONFDIR/config.json
DOCKERJSONCONF1=$CONFDIR/docker.config.json
JSONCONF2=$WEBASSETSCONFDIR/config.json
DOCKERJSONCONF2=$WEBASSETSCONFDIR/docker.config.json
JSONCONF3=$WEBSWAGGERUIDIR/swagger.json
DOCKERJSONCONF3=$WEBSWAGGERUIDIR/docker.swagger.json
JSONCONF4=$WEBASSETSSWAGGERDIR/private-API.json
DOCKERJSONCONF4=$WEBASSETSSWAGGERDIR/docker.private-API.json
CLUSTERCONF=$CONFDIR/cluster.xml
DOCKERCLUSTERCONF=$CONFDIR/docker.cluster.xml
INDEXHTMLEN=$WEBROOTEN/index.html
DOCKERINDEXHTMLEN=$WEBROOTEN/docker.index.html
INDEXHTMLES=$WEBROOTES/index.html
DOCKERINDEXHTMLES=$WEBROOTES/docker.index.html
INDEXHTMLIT=$WEBROOTIT/index.html
DOCKERINDEXHTMLIT=$WEBROOTIT/docker.index.html
INDEXHTMLGL=$WEBROOTGL/index.html
DOCKERINDEXHTMLGL=$WEBROOTGL/docker.index.html
KEYSTOREFILE=./keystore.jks
OAUTH2PROVIDERSFILE=./oauth2providers.json

#BACKUP DIRS AND FILES
PERSISTENTCONFIGDIR=./cpd-configuration

PRODUCTIONFILE_BK=$PERSISTENTCONFIGDIR/.properties
JSONCONF1_BK=$PERSISTENTCONFIGDIR/config_1.json
JSONCONF2_BK=$PERSISTENTCONFIGDIR/config_2.json
JSONCONF3_BK=$PERSISTENTCONFIGDIR/swagger.json
JSONCONF4_BK=$PERSISTENTCONFIGDIR/private-API.json
CLUSTERCONF_BK=$PERSISTENTCONFIGDIR/cluster.xml
INDEXHTMLEN_BK=$PERSISTENTCONFIGDIR/index_en.html
INDEXHTMLES_BK=$PERSISTENTCONFIGDIR/index_es.html
INDEXHTMLIT_BK=$PERSISTENTCONFIGDIR/index_it.html
INDEXHTMLGL_BK=$PERSISTENTCONFIGDIR/index_gl.html
KEYSTOREFILE_BK=$PERSISTENTCONFIGDIR/keystore.jks
OAUTH2PROVIDERSFILE_BK=$PERSISTENTCONFIGDIR/oauth2providers.json
